spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5433/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 9365521165-2uij60qr288tgkga3mrtli5ddr093agg.apps.googleusercontent.com
            client-secret: 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
  logging:
    level:
      org.springframework.security: DEBUG